// <auto-generated />
using System;
using Microsoft.Data.SqlTypes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Srodkowy.Functions.Persistence;

#nullable disable

namespace Srodkowy.Functions.Persistence.Migrations
{
    [DbContext(typeof(SrodkowyDbContext))]
    [Migration("20260406151528_AddSourceDiscoverySelectors")]
    partial class AddSourceDiscoverySelectors
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Srodkowy.Functions.Models.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CleanedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CleanedContentText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CleanupError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CleanupFlagsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("[]");

                    b.Property<string>("CleanupInputHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CleanupProcessor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("CleanupRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CleanupStartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CleanupStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("EmbeddedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<SqlVector<float>?>("Embedding")
                        .HasColumnType("vector(1536)");

                    b.Property<string>("EmbeddingError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbeddingModel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("EmbeddingRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("EmbeddingStartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EmbeddingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("EmbeddingTextHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsProbablyNonArticle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NeedsReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("QualityScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("ScrapedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CleanupRunId");

                    b.HasIndex("CleanupStatus");

                    b.HasIndex("EmbeddingRunId");

                    b.HasIndex("EmbeddingStatus");

                    b.HasIndex("ScrapedAt");

                    b.HasIndex("SourceId");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.HasIndex("CleanupStatus", "ScrapedAt");

                    b.HasIndex("EmbeddingStatus", "ScrapedAt");

                    b.ToTable("Articles", (string)null);
                });

            modelBuilder.Entity("Srodkowy.Functions.Models.CandidateCluster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ArticleCount")
                        .HasColumnType("int");

                    b.Property<double>("BalanceScore")
                        .HasColumnType("float");

                    b.Property<Guid>("ClusterRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DistinctSourceCount")
                        .HasColumnType("int");

                    b.Property<int>("LeftArticleCount")
                        .HasColumnType("int");

                    b.Property<double>("MeanSimilarity")
                        .HasColumnType("float");

                    b.Property<double>("NarrativeDivergenceScore")
                        .HasColumnType("float");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<double>("RankScore")
                        .HasColumnType("float");

                    b.Property<Guid>("RepresentativeArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RightArticleCount")
                        .HasColumnType("int");

                    b.Property<string>("SelectionVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("WindowEndAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("WindowStartAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ClusterRunId");

                    b.HasIndex("Rank");

                    b.HasIndex("RepresentativeArticleId");

                    b.HasIndex("Status");

                    b.ToTable("CandidateClusters", (string)null);
                });

            modelBuilder.Entity("Srodkowy.Functions.Models.CandidateClusterArticle", b =>
                {
                    b.Property<Guid>("CandidateClusterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Camp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsRepresentative")
                        .HasColumnType("bit");

                    b.Property<double>("SimilarityToRepresentative")
                        .HasColumnType("float");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CandidateClusterId", "ArticleId");

                    b.HasIndex("ArticleId");

                    b.ToTable("CandidateClusterArticles", (string)null);
                });

            modelBuilder.Entity("Srodkowy.Functions.Models.ClusterRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CandidateArticleCount")
                        .HasColumnType("int");

                    b.Property<int>("ClusterCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DeduplicatedArticleCount")
                        .HasColumnType("int");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LookbackHours")
                        .HasColumnType("int");

                    b.Property<int>("QualifiedClusterCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("ClusterRuns", (string)null);
                });

            modelBuilder.Entity("Srodkowy.Functions.Models.IngestionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ArticleCount")
                        .HasColumnType("int");

                    b.Property<int>("CandidateLinkCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DiscoveredLinkCount")
                        .HasColumnType("int");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("IngestionRuns", (string)null);
                });

            modelBuilder.Entity("Srodkowy.Functions.Models.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Camp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiscoveryExcludeTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscoveryIncludeTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscoveryUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("BaseUrl")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dbcd8890-2997-4016-af5f-8d244e2d980c"),
                            Active = true,
                            BaseUrl = "https://onet.pl",
                            Camp = "left",
                            DiscoveryUrl = "https://www.onet.pl",
                            Name = "Onet.pl"
                        },
                        new
                        {
                            Id = new Guid("21fcd750-a76d-418e-ace0-1ced0c5e2b39"),
                            Active = true,
                            BaseUrl = "https://gazeta.pl",
                            Camp = "left",
                            DiscoveryUrl = "https://wiadomosci.gazeta.pl",
                            Name = "Gazeta.pl"
                        },
                        new
                        {
                            Id = new Guid("ed1ccaf0-2bf3-4faf-a660-80dba33908bd"),
                            Active = true,
                            BaseUrl = "https://natemat.pl",
                            Camp = "left",
                            DiscoveryUrl = "https://natemat.pl",
                            Name = "Natemat.pl"
                        },
                        new
                        {
                            Id = new Guid("a3daa853-f462-4953-8cf0-1f26c9b8b1c3"),
                            Active = true,
                            BaseUrl = "https://krytykapolityczna.pl",
                            Camp = "left",
                            DiscoveryUrl = "https://krytykapolityczna.pl",
                            Name = "Krytykapolityczna.pl"
                        },
                        new
                        {
                            Id = new Guid("6d5017af-2316-4c54-8079-80b8988f6ca5"),
                            Active = true,
                            BaseUrl = "https://oko.press",
                            Camp = "left",
                            DiscoveryUrl = "https://oko.press",
                            Name = "Oko.press"
                        },
                        new
                        {
                            Id = new Guid("925c5ed1-cfd0-4090-9c18-5ef0b24264bc"),
                            Active = true,
                            BaseUrl = "https://newsweek.pl",
                            Camp = "left",
                            DiscoveryUrl = "https://www.newsweek.pl",
                            Name = "Newsweek.pl"
                        },
                        new
                        {
                            Id = new Guid("4e673eb2-00b7-4b8d-a89b-451e19b04174"),
                            Active = true,
                            BaseUrl = "https://polityka.pl",
                            Camp = "left",
                            DiscoveryUrl = "https://www.polityka.pl",
                            Name = "Polityka.pl"
                        },
                        new
                        {
                            Id = new Guid("21ba4856-b5bb-4121-b812-be8e4f429914"),
                            Active = true,
                            BaseUrl = "https://tvn24.pl",
                            Camp = "left",
                            DiscoveryUrl = "https://tvn24.pl",
                            Name = "Tvn24.pl"
                        },
                        new
                        {
                            Id = new Guid("71eb6457-b3a4-4545-9c63-134b709beae7"),
                            Active = true,
                            BaseUrl = "https://tokfm.pl",
                            Camp = "left",
                            DiscoveryUrl = "https://www.tokfm.pl",
                            Name = "Tokfm.pl"
                        },
                        new
                        {
                            Id = new Guid("1b706c1f-08a6-44c3-9dbe-abdb3f0e1921"),
                            Active = true,
                            BaseUrl = "https://strajk.eu",
                            Camp = "left",
                            DiscoveryUrl = "https://strajk.eu",
                            Name = "Strajk.eu"
                        },
                        new
                        {
                            Id = new Guid("21236d5c-52b3-467b-8052-08f0018d245b"),
                            Active = true,
                            BaseUrl = "https://trybuna.info",
                            Camp = "left",
                            DiscoveryUrl = "https://trybuna.info",
                            Name = "Trybuna.info"
                        },
                        new
                        {
                            Id = new Guid("8934e6e3-3cea-4717-8782-d2996d19ffb8"),
                            Active = true,
                            BaseUrl = "https://niezalezna.pl",
                            Camp = "right",
                            DiscoveryUrl = "https://niezalezna.pl",
                            Name = "Niezalezna.pl"
                        },
                        new
                        {
                            Id = new Guid("db3f3b4c-27b7-4ac3-8a21-f94d5c74447c"),
                            Active = true,
                            BaseUrl = "https://wpolityce.pl",
                            Camp = "right",
                            DiscoveryUrl = "https://wpolityce.pl",
                            Name = "Wpolityce.pl"
                        },
                        new
                        {
                            Id = new Guid("36941f6c-8d76-45b5-81d9-fcfac1278bfc"),
                            Active = true,
                            BaseUrl = "https://dorzeczy.pl",
                            Camp = "right",
                            DiscoveryUrl = "https://dorzeczy.pl",
                            Name = "Dorzeczy.pl"
                        },
                        new
                        {
                            Id = new Guid("c57f4d5d-405f-4336-9156-8a5bf388c889"),
                            Active = true,
                            BaseUrl = "https://prawy.pl",
                            Camp = "right",
                            DiscoveryUrl = "https://prawy.pl",
                            Name = "Prawy.pl"
                        },
                        new
                        {
                            Id = new Guid("06f296d0-9a17-4446-a800-b9cd969aec68"),
                            Active = true,
                            BaseUrl = "https://tvrepublika.pl",
                            Camp = "right",
                            DiscoveryIncludeTags = "[\"main\"]",
                            DiscoveryUrl = "https://tvrepublika.pl/tag/Wydarzenia-dnia",
                            Name = "Tvrepublika.pl"
                        },
                        new
                        {
                            Id = new Guid("4fbdb458-fa8b-40ae-b177-f566ebca757f"),
                            Active = true,
                            BaseUrl = "https://radiomaryja.pl",
                            Camp = "right",
                            DiscoveryUrl = "https://www.radiomaryja.pl",
                            Name = "Radiomaryja.pl"
                        },
                        new
                        {
                            Id = new Guid("422dead7-b6d9-468f-beaf-eb3419dd17f1"),
                            Active = true,
                            BaseUrl = "https://tysol.pl",
                            Camp = "right",
                            DiscoveryUrl = "https://www.tysol.pl",
                            Name = "Tysol.pl"
                        },
                        new
                        {
                            Id = new Guid("c1f7c30a-3680-49f8-9763-72e97bc5bf1b"),
                            Active = true,
                            BaseUrl = "https://pch24.pl",
                            Camp = "right",
                            DiscoveryUrl = "https://pch24.pl",
                            Name = "PCh24.pl"
                        });
                });

            modelBuilder.Entity("Srodkowy.Functions.Models.Article", b =>
                {
                    b.HasOne("Srodkowy.Functions.Models.Source", "Source")
                        .WithMany("Articles")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Srodkowy.Functions.Models.CandidateCluster", b =>
                {
                    b.HasOne("Srodkowy.Functions.Models.ClusterRun", "ClusterRun")
                        .WithMany("CandidateClusters")
                        .HasForeignKey("ClusterRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Srodkowy.Functions.Models.Article", "RepresentativeArticle")
                        .WithMany()
                        .HasForeignKey("RepresentativeArticleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ClusterRun");

                    b.Navigation("RepresentativeArticle");
                });

            modelBuilder.Entity("Srodkowy.Functions.Models.CandidateClusterArticle", b =>
                {
                    b.HasOne("Srodkowy.Functions.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Srodkowy.Functions.Models.CandidateCluster", "CandidateCluster")
                        .WithMany("Articles")
                        .HasForeignKey("CandidateClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("CandidateCluster");
                });

            modelBuilder.Entity("Srodkowy.Functions.Models.CandidateCluster", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Srodkowy.Functions.Models.ClusterRun", b =>
                {
                    b.Navigation("CandidateClusters");
                });

            modelBuilder.Entity("Srodkowy.Functions.Models.Source", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
